### ISSUE TITLE
Adding screenshots to your readme....

### ISSUE THREAD

**Issue by PySimpleGUI** [Ciuel/Python-Grupo12#2]
I grabbed the screenshots posted on Twitter and am pasting them here:

![image](https://user-images.githubusercontent.com/46163555/123527387-19795380-d6ad-11eb-85f6-05ef45bc579a.png)
![image](https://user-images.githubusercontent.com/46163555/123527397-3b72d600-d6ad-11eb-92ab-245188ebeb0a.png)
![image](https://user-images.githubusercontent.com/46163555/123527403-40378a00-d6ad-11eb-98cb-fe63a6081d75.png)
![image](https://user-images.githubusercontent.com/46163555/123527406-46c60180-d6ad-11eb-8ee7-2d9e07154f83.png)

You can edit the issue and get these lines from it:
```

![image](https://user-images.githubusercontent.com/46163555/123527387-19795380-d6ad-11eb-85f6-05ef45bc579a.png)
![image](https://user-images.githubusercontent.com/46163555/123527397-3b72d600-d6ad-11eb-92ab-245188ebeb0a.png)
![image](https://user-images.githubusercontent.com/46163555/123527403-40378a00-d6ad-11eb-98cb-fe63a6081d75.png)
![image](https://user-images.githubusercontent.com/46163555/123527406-46c60180-d6ad-11eb-8ee7-2d9e07154f83.png)
```

And then paste them into your readme.  They will show up as embedded images in your readme.  

GitHub Issues are a cheap way to host images on the Internet!

**Comment by Vinegar-Doppio1** [comment]
Thanks! I was doing the same :)

**Comment by PySimpleGUI** [comment]
It's a great trick.

I kinda lucked onto it.  I started doing it to get images to post on Reddit. 

Then I noticed that the format that GitHub was using in the Issue was the same as the readme markdown (I was new to markdown at that time and pretty ignorant about everything) and so I pasted the lines into my readme and was shocked it see it worked.

**Comment by PySimpleGUI** [comment]
Nice!  Looks great!!
